micronaut:
  application:
    name: productsService

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/productdatabase
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
