create table product (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    price float not null,
    quantity_in_stock integer not null,
    constraint id unique(id)
);

insert into product(id, name, price, quantity_in_stock) values(1, 'product 1', 10.99, 10);
insert into product(id, name, price, quantity_in_stock) values(2, 'product 2', 10.99, 10);